### ISSUE TITLE
ValueError("No such tool " + tool_name) Erro happened when running the par of Rocket chip with OpenROAD in Hammer

### ISSUE THREAD

**Issue by JiaDYuan** [ucb-bar/hammer#665]
I was trying to running the VLSI flow of RocketChip through OpenROAD tool in Hammer. The synthesis has passed. However, the P&R failed. Here are the error messages:

[<global>] Loading hammer-vlsi libraries and reading settings
[<global>] Loading technology 'nangate45'
Traceback (most recent call last):
  File "/home/yuanjiadong/chipyard/vlsi/hammer/src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py", line 1661, in load_tool
    mod = importlib.import_module(tool_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openroad'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuanjiadong/chipyard/vlsi/./example-vlsi", line 62, in <module>
    ExampleDriver().main()
  File "/home/yuanjiadong/chipyard/vlsi/hammer/src/hammer-vlsi/hammer_vlsi/cli_driver.py", line 1360, in main
    sys.exit(self.run_main_parsed(vars(parser.parse_args(args))))
  File "/home/yuanjiadong/chipyard/vlsi/hammer/src/hammer-vlsi/hammer_vlsi/cli_driver.py", line 1267, in run_main_parsed
    output_config = action_func(driver, errors.append)  # type: Optional[dict]
  File "/home/yuanjiadong/chipyard/vlsi/hammer/src/hammer-vlsi/hammer_vlsi/cli_driver.py", line 451, in action
    if not driver.load_par_tool(get_or_else(self.par_rundir, "")):
  File "/home/yuanjiadong/chipyard/vlsi/hammer/src/hammer-vlsi/hammer_vlsi/driver.py", line 319, in load_par_tool
    config_result = self.instantiate_tool_from_config("par", HammerPlaceAndRouteTool)
  File "/home/yuanjiadong/chipyard/vlsi/hammer/src/hammer-vlsi/hammer_vlsi/driver.py", line 183, in instantiate_tool_from_config
    tool_get = load_tool(
  File "/home/yuanjiadong/chipyard/vlsi/hammer/src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py", line 1663, in load_tool
    raise ValueError("No such tool " + tool_name)
ValueError: No such tool openroad
make: *** [/home/yuanjiadong/chipyard/vlsi/build/chipyard.TestHarness.RocketConfig-ChipTop/hammer.d:65: /home/yuanjiadong/chipyard/vlsi/build/chipyard.TestHarness.RocketConfig-ChipTop/par-rundir/par-output-full.json] Error 1

**Comment by nayiri-k** [comment]
In your YAML config file, did you specify the path to openroad as something like this:
```
# OpenROAD-par options
vlsi.core.par_tool: "openroad"
vlsi.core.par_tool_path: ["hammer/src/hammer-vlsi/par"]
vlsi.core.par_tool_path_meta: "append"
```
and make sure that this directory exists: `{vlsi.core.par_tool_path}/openroad`.
