### ISSUE TITLE
AttributeError: module 'openroad' has no attribute 'tool' Erro happened when running the sky130-openroad example in hammer

### ISSUE THREAD

**Issue by ZhaoHaowenn** [ucb-bar/hammer#715]
The chipyard version is 1.8.1 and hammer version is 0.1.0.  I specifid the path to openroad in example-openroad.yml. And The synthesis has passed. But make par tutorial=ky130-openroad failed. Here are the error messages:

  File "/root/chipyard/vlsi/hammer/src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py", line 2163, in load_tool
    tool_class = getattr(mod, "tool")
AttributeError: module 'openroad' has no attribute 'tool'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/chipyard/vlsi/./example-vlsi-sky130", line 64, in <module>
    ExampleDriver().main()
  File "/root/chipyard/vlsi/hammer/src/hammer-vlsi/hammer_vlsi/cli_driver.py", line 1669, in main
    sys.exit(self.run_main_parsed(vars(parser.parse_args(args))))
  File "/root/chipyard/vlsi/hammer/src/hammer-vlsi/hammer_vlsi/cli_driver.py", line 1572, in run_main_parsed
    output_config = action_func(driver, errors.append)  # type: Optional[dict]
  File "/root/chipyard/vlsi/hammer/src/hammer-vlsi/hammer_vlsi/cli_driver.py", line 556, in action
    if not driver.load_par_tool(get_or_else(self.par_rundir, "")):
  File "/root/chipyard/vlsi/hammer/src/hammer-vlsi/hammer_vlsi/driver.py", line 323, in load_par_tool
    config_result = self.instantiate_tool_from_config("par", HammerPlaceAndRouteTool)
  File "/root/chipyard/vlsi/hammer/src/hammer-vlsi/hammer_vlsi/driver.py", line 187, in instantiate_tool_from_config
    tool_get = load_tool(
  File "/root/chipyard/vlsi/hammer/src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py", line 2165, in load_tool
    raise ValueError("No such tool " + tool_name + ", or tool does not follow the hammer-vlsi tool library format")
ValueError: No such tool openroad, or tool does not follow the hammer-vlsi tool library format
make: *** [/root/chipyard/vlsi/build-sky130-openroad/chipyard.TestHarness.TinyRocketConfig-ChipTop/hammer.d:94: /root/chipyard/vlsi/build-sky130-openroad/chipyard.TestHarness.TinyRocketConfig-ChipTop/par-rundir/par-output-full.json] Error 1
How should I run without error? Or should I update to the latest hammer？

**Comment by nayiri-k** [comment]
Hello, this might be a chipyard vs hammer version issue. In your `example-openroad.yml` file, does the par YAML key look like this:

```
vlsi.core.par_tool: "hammer.par.openroad"
```

Or like this:
```
vlsi.core.par_tool: "openroad"
vlsi.core.par_tool_path: ["hammer/src/hammer-vlsi/par"]
vlsi.core.par_tool_path_meta: "append"
```
Because if the `~chipyard/vlsi/hammer/src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py` file is being called it expects the latter format, but we switched to use the much-simplified first format.

I will also mention, we are about to push many changes to the sky130+openroad tutorial flow in the next chipyard release happening this week that will significantly improve results. So it may be worthwhile to wait for those changes.
